import { useEffect, useState } from "react";
import { supabase } from "../lib/supabaseClient";
import { useRouter } from "next/router";

export default function Admin() {
  const router = useRouter();

  const [jobs, setJobs] = useState([]);
  const [form, setForm] = useState({});

  useEffect(() => {
    init();
  }, []);

  async function init() {
    const { data } = await supabase.auth.getUser();

    if (!data.user) return router.push("/login");

    if (data.user.email !== "amardeus02@gmail.com") {
      return router.push("/dashboard");
    }

    fetchJobs();
  }

  async function fetchJobs() {
    const { data } = await supabase
      .from("jobs")
      .select("*")
      .order("created_at", { ascending: false });

    setJobs(data || []);
  }

  function handleChange(e, id) {
    setForm({
      ...form,
      [id]: {
        ...form[id],
        [e.target.name]: e.target.value
      }
    });
  }

  async function save(id) {
    const data = form[id];
    if (!data) return alert("Fill classification");

    const job = jobs.find(j => j.id === id);

    const html = `
      <h1>Dangerous Goods Declaration</h1>
      <p><strong>Product:</strong> ${job.product_name}</p>
      <p><strong>Company:</strong> ${job.company}</p>
      <p><strong>UN:</strong> ${data.un_number}</p>
      <p><strong>Class:</strong> ${data.hazard_class}</p>
      <p><strong>Packing Group:</strong> ${data.packing_group}</p>
      <p><strong>EMS:</strong> ${data.ems}</p>
      <p><strong>Limited Quantity:</strong> ${data.limited_quantity}</p>
      <p><strong>Aerosol:</strong> ${data.aerosol}</p>
      <p><strong>Flammable:</strong> ${data.flammable}</p>
      <p><strong>Flash Point:</strong> ${data.flash_point}</p>
      <hr/>
      <p>Generated by DGRFlow</p>
    `;

    const blob = new Blob([html], { type: "text/html" });
    const filePath = `result_${Date.now()}.html`;

    const { error: uploadError } = await supabase.storage
      .from("results")
      .upload(filePath, blob);

    if (uploadError) return alert(uploadError.message);

    const { error } = await supabase
      .from("jobs")
      .update({
        ...data,
        result_file: filePath,
        status: "done"
      })
      .eq("id", id);

    if (error) return alert(error.message);

    alert("Documento gerado 🚀");
    fetchJobs();
  }

  return (
    <div style={{ padding: 40 }}>

      {/* HEADER */}
      <div style={{ display: "flex", justifyContent: "space-between", marginBottom: 20 }}>
        <h1>Admin - Classification</h1>

        <button onClick={() => router.push("/dashboard")}>
          ← Back to Dashboard
        </button>
      </div>

      {jobs.map((job) => (
        <div key={job.id} style={card}>

          <h3>{job.product_name}</h3>
          <p>{job.company}</p>

          <div style={grid}>

            <input name="un_number" placeholder="UN Number" onChange={(e) => handleChange(e, job.id)} style={input}/>
            <input name="hazard_class" placeholder="Hazard Class" onChange={(e) => handleChange(e, job.id)} style={input}/>
            <input name="packing_group" placeholder="Packing Group" onChange={(e) => handleChange(e, job.id)} style={input}/>
            <input name="ems" placeholder="EMS" onChange={(e) => handleChange(e, job.id)} style={input}/>
            <input name="flash_point" placeholder="Flash Point (°C)" onChange={(e) => handleChange(e, job.id)} style={input}/>

            <select name="limited_quantity" onChange={(e) => handleChange(e, job.id)} style={input}>
              <option value="">Limited Quantity?</option>
              <option value="yes">Yes</option>
              <option value="no">No</option>
            </select>

            <select name="aerosol" onChange={(e) => handleChange(e, job.id)} style={input}>
              <option value="">Aerosol?</option>
              <option value="yes">Yes</option>
              <option value="no">No</option>
            </select>

            <select name="flammable" onChange={(e) => handleChange(e, job.id)} style={input}>
              <option value="">Flammable?</option>
              <option value="yes">Yes</option>
              <option value="no">No</option>
            </select>

          </div>

          <button onClick={() => save(job.id)} style={btn}>
            Generate Document
          </button>

        </div>
      ))}

    </div>
  );
}

/* STYLES */

const card = {
  background: "#0f172a",
  padding: 20,
  borderRadius: 12,
  marginBottom: 20,
  color: "white"
};

const grid = {
  display: "grid",
  gridTemplateColumns: "repeat(3, 1fr)",
  gap: 10
};

const input = {
  padding: 10,
  borderRadius: 8,
  border: "1px solid #334155",
  background: "#020617",
  color: "white"
};

const btn = {
  marginTop: 15,
  padding: 10,
  background: "#7c3aed",
  border: "none",
  color: "white",
  borderRadius: 8
};
