import PDFDocument from "pdfkit";

export default async function handler(req, res) {
  try {
    if (req.method !== "POST") {
      return res.status(405).json({
        success: false,
        error: "Method not allowed",
      });
    }

    const { sds, classification, validation } = req.body;

    const dg = classification?.classification || classification || {};

    const validationData = validation?.validation || validation || {};

    const doc = new PDFDocument({
      size: "A4",
      margin: 40,
    });

    const buffers = [];

    doc.on("data", buffers.push.bind(buffers));

    doc.on("end", () => {
      const pdfData = Buffer.concat(buffers);

      res.writeHead(200, {
        "Content-Type": "application/pdf",
        "Content-Disposition": "attachment; filename=IMO_Dangerous_Goods_Declaration.pdf",
        "Content-Length": pdfData.length,
      });

      res.end(pdfData);
    });

    // =========================
    // HEADER
    // =========================

    doc
      .fontSize(20)
      .font("Helvetica-Bold")
      .text("IMO DANGEROUS GOODS DECLARATION", {
        align: "center",
      });

    doc.moveDown(0.5);

    doc
      .fontSize(10)
      .font("Helvetica")
      .text("Generated by DGRFlow - Dangerous Goods Automation Platform", {
        align: "center",
      });

    doc.moveDown(1.2);

    // =========================
    // DOCUMENT INFO
    // =========================

    doc
      .fontSize(12)
      .font("Helvetica-Bold")
      .text("Document Information");

    doc.moveDown(0.5);

    doc
      .fontSize(10)
      .font("Helvetica")
      .text(`Generated Date: ${new Date().toLocaleDateString()}`)
      .text(`Generated Time: ${new Date().toLocaleTimeString()}`)
      .text("Document Type: IMO Dangerous Goods Declaration");

    doc.moveDown(1);

    // =========================
    // SHIPPER / CONSIGNEE
    // =========================

    doc
      .fontSize(12)
      .font("Helvetica-Bold")
      .text("Shipper / Consignee Information");

    doc.moveDown(0.5);

    doc
      .fontSize(10)
      .font("Helvetica")
      .text("Shipper: ________________________________")
      .text("Consignee: ______________________________")
      .text("Booking / BOL: __________________________")
      .text("Vessel / Voyage: ________________________")
      .text("Port of Loading: ________________________")
      .text("Port of Discharge: ______________________");

    doc.moveDown(1);

    // =========================
    // DG CLASSIFICATION
    // =========================

    doc
      .fontSize(12)
      .font("Helvetica-Bold")
      .text("Dangerous Goods Classification");

    doc.moveDown(0.5);

    const dgRows = [
      ["UN Number", dg.un_number || "N/A"],
      ["Proper Shipping Name", dg.proper_shipping_name || "N/A"],
      ["Hazard Class", dg.hazard_class || "N/A"],
      ["Packing Group", dg.packing_group || "N/A"],
      ["Marine Pollutant", dg.marine_pollutant || "N/A"],
      ["Tunnel Code", dg.tunnel_code || "N/A"],
      ["Limited Quantity", dg.limited_quantity || "N/A"],
      ["Excepted Quantity", dg.excepted_quantity || "N/A"],
      ["Segregation", dg.segregation || "N/A"],
    ];

    dgRows.forEach(([label, value]) => {
      doc
        .fontSize(10)
        .font("Helvetica-Bold")
        .text(`${label}: `, {
          continued: true,
        })
        .font("Helvetica")
        .text(String(value));
    });

    doc.moveDown(1);

    // =========================
    // LABELS
    // =========================

    doc
      .fontSize(12)
      .font("Helvetica-Bold")
      .text("Required Labels / Marks");

    doc.moveDown(0.5);

    if (Array.isArray(dg.labels) && dg.labels.length > 0) {
      dg.labels.forEach((label) => {
        doc
          .fontSize(10)
          .font("Helvetica")
          .text(`• Label ${label}`);
      });
    } else {
      doc
        .fontSize(10)
        .font("Helvetica")
        .text("No labels identified.");
    }

    doc.moveDown(1);

    // =========================
    // VALIDATION
    // =========================

    doc
      .fontSize(12)
      .font("Helvetica-Bold")
      .text("DG Validation Summary");

    doc.moveDown(0.5);

    doc
      .fontSize(10)
      .font("Helvetica")
      .text(`Validation Status: ${validationData.status || "N/A"}`)
      .text(`Approved: ${validationData.approved ? "Yes" : "No"}`)
      .text(`Message: ${validationData.message || "N/A"}`);

    doc.moveDown(0.5);

    if (Array.isArray(validationData.errors) && validationData.errors.length > 0) {
      doc
        .fontSize(10)
        .font("Helvetica-Bold")
        .text("Errors:");

      validationData.errors.forEach((err) => {
        doc
          .fontSize(10)
          .font("Helvetica")
          .text(`• ${err}`);
      });
    }

    if (Array.isArray(validationData.warnings) && validationData.warnings.length > 0) {
      doc.moveDown(0.5);

      doc
        .fontSize(10)
        .font("Helvetica-Bold")
        .text("Warnings:");

      validationData.warnings.forEach((warning) => {
        doc
          .fontSize(10)
          .font("Helvetica")
          .text(`• ${warning}`);
      });
    }

    doc.moveDown(1);

    // =========================
    // DECLARATION
    // =========================

    doc
      .fontSize(12)
      .font("Helvetica-Bold")
      .text("Declaration");

    doc.moveDown(0.5);

    doc
      .fontSize(10)
      .font("Helvetica")
      .text(
        "I hereby declare that the contents of this consignment are fully and accurately described above by the proper shipping name, and are classified, packaged, marked and labelled/placarded, and are in all respects in proper condition for transport according to applicable international and national governmental regulations.",
        {
          align: "justify",
        }
      );

    doc.moveDown(1.5);

    doc
      .fontSize(10)
      .font("Helvetica")
      .text("Name / Title of Signatory: ____________________________")
      .moveDown(0.5)
      .text("Place and Date: _______________________________________")
      .moveDown(0.5)
      .text("Signature: ____________________________________________");

    doc.moveDown(1);

    // =========================
    // FOOTER
    // =========================

    doc
      .fontSize(8)
      .font("Helvetica")
      .fillColor("gray")
      .text(
        "This document was generated automatically by DGRFlow. Final regulatory review by a qualified dangerous goods professional is recommended before shipment.",
        {
          align: "center",
        }
      );

    doc.end();
  } catch (error) {
    console.error("GENERATE PDF API ERROR:", error);

    return res.status(500).json({
      success: false,
      error: error.message || "PDF generation failed",
    });
  }
}
