import { useEffect, useState } from "react";
import { supabase } from "../lib/supabaseClient";
import { useRouter } from "next/router";

export default function Admin() {
  const router = useRouter();

  const [jobs, setJobs] = useState([]);
  const [form, setForm] = useState({});
  const [pdfReady, setPdfReady] = useState(false);

  useEffect(() => {
    init();
    loadPDF();
  }, []);

  async function init() {
    const { data } = await supabase.auth.getUser();

    if (!data.user) return router.push("/login");

    if (data.user.email !== "amardeus02@gmail.com") {
      return router.push("/dashboard");
    }

    fetchJobs();
  }

  function loadPDF() {
    if (window.jspdf) {
      setPdfReady(true);
      return;
    }

    const script = document.createElement("script");
    script.src =
      "https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js";
    script.onload = () => setPdfReady(true);
    document.body.appendChild(script);
  }

  async function fetchJobs() {
    const { data } = await supabase
      .from("jobs")
      .select("*")
      .order("created_at", { ascending: false });

    setJobs(data || []);
  }

  function handleChange(e, id) {
    setForm({
      ...form,
      [id]: {
        ...form[id],
        [e.target.name]: e.target.value,
      },
    });
  }

  // AUTO CLASSIFICATION
  function autoClassify(data) {
    let result = { ...data };

    if (data.flammable === "yes") result.hazard_class = "3";
    if (data.aerosol === "yes") result.hazard_class = "2";

    const fp = parseFloat(data.flash_point);

    if (!isNaN(fp)) {
      if (fp < 23) result.packing_group = "II";
      else if (fp <= 60) result.packing_group = "III";
    }

    return result;
  }

  // GENERATE PDF
  async function save(id) {
    if (!pdfReady) return alert("PDF ainda carregando...");

    let data = form[id];
    if (!data) return alert("Fill classification");

    data = autoClassify(data);

    const job = jobs.find((j) => j.id === id);

    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();

    let y = 15;

    // HEADER
    doc.setFontSize(18);
    doc.setFont(undefined, "bold");
    doc.text("DGRFlow", 10, y);

    doc.setFontSize(12);
    doc.setFont(undefined, "normal");
    doc.text("Dangerous Goods Declaration", 200, y, { align: "right" });

    y += 10;

    doc.setDrawColor(200);
    doc.line(10, y, 200, y);

    y += 10;

    // PRODUCT SECTION
    doc.setFont(undefined, "bold");
    doc.text("Product Information", 10, y);
    y += 8;

    doc.setFont(undefined, "normal");
    doc.text(`Product: ${job.product_name}`, 10, y); y += 6;
    doc.text(`Company: ${job.company}`, 10, y); y += 10;

    // CLASSIFICATION
    doc.setFont(undefined, "bold");
    doc.text("Classification", 10, y);
    y += 8;

    doc.setFont(undefined, "normal");

    doc.text("UN Number:", 10, y);
    doc.text(`${data.un_number || "-"}`, 80, y);
    y += 6;

    doc.text("Hazard Class:", 10, y);
    doc.text(`${data.hazard_class || "-"}`, 80, y);
    y += 6;

    doc.text("Packing Group:", 10, y);
    doc.text(`${data.packing_group || "-"}`, 80, y);
    y += 6;

    doc.text("EMS:", 10, y);
    doc.text(`${data.ems || "-"}`, 80, y);
    y += 10;

    // TRANSPORT
    doc.setFont(undefined, "bold");
    doc.text("Transport Details", 10, y);
    y += 8;

    doc.setFont(undefined, "normal");

    doc.text("Limited Quantity:", 10, y);
    doc.text(`${data.limited_quantity || "-"}`, 80, y);
    y += 6;

    doc.text("Aerosol:", 10, y);
    doc.text(`${data.aerosol || "-"}`, 80, y);
    y += 6;

    doc.text("Flammable:", 10, y);
    doc.text(`${data.flammable || "-"}`, 80, y);
    y += 6;

    doc.text("Flash Point:", 10, y);
    doc.text(`${data.flash_point || "-"} °C`, 80, y);
    y += 10;

    // FOOTER
    doc.setDrawColor(200);
    doc.line(10, y, 200, y);

    y += 6;

    doc.setFontSize(10);
    doc.text("Generated by DGRFlow", 10, y);

    const pdfBlob = doc.output("blob");
    const filePath = `result_${Date.now()}.pdf`;

    const { error: uploadError } = await supabase.storage
      .from("results")
      .upload(filePath, pdfBlob);

    if (uploadError) return alert(uploadError.message);

    const { error } = await supabase
      .from("jobs")
      .update({
        ...data,
        result_file: filePath,
        status: "done",
      })
      .eq("id", id);

    if (error) return alert(error.message);

    alert("PDF profissional gerado 🚀");

    fetchJobs();
  }

  return (
    <div style={container}>
      <div style={header}>
        <h1>Admin - Classification</h1>

        <button onClick={() => router.push("/dashboard")} style={backBtn}>
          ← Back
        </button>
      </div>

      {jobs.map((job) => (
        <div key={job.id} style={card}>
          <h3>{job.product_name}</h3>
          <p style={{ opacity: 0.6 }}>{job.company}</p>

          <div style={grid}>
            <input name="un_number" placeholder="UN Number" onChange={(e) => handleChange(e, job.id)} style={input}/>
            <input name="hazard_class" placeholder="Hazard Class" onChange={(e) => handleChange(e, job.id)} style={input}/>
            <input name="packing_group" placeholder="Packing Group" onChange={(e) => handleChange(e, job.id)} style={input}/>

            <input name="ems" placeholder="EMS" onChange={(e) => handleChange(e, job.id)} style={input}/>
            <input name="flash_point" placeholder="Flash Point (°C)" onChange={(e) => handleChange(e, job.id)} style={input}/>

            <select name="limited_quantity" onChange={(e) => handleChange(e, job.id)} style={input}>
              <option value="">Limited Quantity?</option>
              <option value="yes">Yes</option>
              <option value="no">No</option>
            </select>

            <select name="aerosol" onChange={(e) => handleChange(e, job.id)} style={input}>
              <option value="">Aerosol?</option>
              <option value="yes">Yes</option>
              <option value="no">No</option>
            </select>

            <select name="flammable" onChange={(e) => handleChange(e, job.id)} style={input}>
              <option value="">Flammable?</option>
              <option value="yes">Yes</option>
              <option value="no">No</option>
            </select>
          </div>

          <button onClick={() => save(job.id)} style={btn}>
            Generate PDF
          </button>
        </div>
      ))}
    </div>
  );
}

/* STYLES */

const container = {
  padding: 40,
  background: "#020617",
  minHeight: "100vh",
  color: "white",
};

const header = {
  display: "flex",
  justifyContent: "space-between",
  marginBottom: 30,
};

const backBtn = {
  padding: 10,
  background: "#334155",
  color: "white",
  border: "none",
  borderRadius: 8,
};

const card = {
  background: "#0f172a",
  padding: 20,
  borderRadius: 12,
  marginBottom: 20,
};

const grid = {
  display: "grid",
  gridTemplateColumns: "repeat(3, 1fr)",
  gap: 10,
};

const input = {
  padding: 10,
  borderRadius: 8,
  border: "1px solid #334155",
  background: "#020617",
  color: "white",
};

const btn = {
  marginTop: 15,
  padding: 12,
  background: "#7c3aed",
  border: "none",
  color: "white",
  borderRadius: 8,
  fontWeight: "bold",
};
