import { useEffect, useState } from "react";
import { supabase } from "../lib/supabaseClient";
import { useRouter } from "next/router";

export default function Admin() {
  const router = useRouter();

  const [jobs, setJobs] = useState([]);
  const [form, setForm] = useState({});

  useEffect(() => {
    init();
  }, []);

  async function init() {
    const { data } = await supabase.auth.getUser();

    if (!data.user) return router.push("/login");

    if (data.user.email !== "amardeus02@gmail.com") {
      return router.push("/dashboard");
    }

    fetchJobs();
  }

  async function fetchJobs() {
    const { data } = await supabase
      .from("jobs")
      .select("*")
      .order("created_at", { ascending: false });

    setJobs(data || []);
  }

  function handleChange(e, id) {
    setForm({
      ...form,
      [id]: {
        ...form[id],
        [e.target.name]: e.target.value
      }
    });
  }

  async function save(id) {
    const data = form[id];
    if (!data) return alert("Fill classification");

    const job = jobs.find(j => j.id === id);

    const html = `
      <h1>Dangerous Goods Declaration</h1>
      <p><strong>Product:</strong> ${job.product_name}</p>
      <p><strong>Company:</strong> ${job.company}</p>
      <p><strong>UN:</strong> ${data.un_number}</p>
      <p><strong>PSN:</strong> ${data.psn}</p>
      <p><strong>Class:</strong> ${data.hazard_class}</p>
      <p><strong>Packing Group:</strong> ${data.packing_group}</p>
      <hr/>
      <p>Generated by DGRFlow</p>
    `;

    const blob = new Blob([html], { type: "text/html" });
    const filePath = `result_${Date.now()}.html`;

    const { error: uploadError } = await supabase.storage
      .from("results")
      .upload(filePath, blob);

    if (uploadError) return alert(uploadError.message);

    const { error } = await supabase
      .from("jobs")
      .update({
        ...data,
        result_file: filePath,
        status: "done"
      })
      .eq("id", id);

    if (error) return alert(error.message);

    alert("Documento gerado 🚀");
    fetchJobs();
  }

  return (
    <div style={{ padding: 40 }}>

      <h1>Admin - Classification</h1>

      {jobs.map((job) => (
        <div key={job.id} style={{ marginBottom: 20 }}>

          <h3>{job.product_name}</h3>

          <input name="un_number" placeholder="UN Number" onChange={(e) => handleChange(e, job.id)} />
          <input name="psn" placeholder="PSN" onChange={(e) => handleChange(e, job.id)} />
          <input name="hazard_class" placeholder="Hazard Class" onChange={(e) => handleChange(e, job.id)} />
          <input name="packing_group" placeholder="Packing Group" onChange={(e) => handleChange(e, job.id)} />

          <button onClick={() => save(job.id)}>
            Generate Document
          </button>

        </div>
      ))}

    </div>
  );
}
